### ISSUE TITLE
biorxiv URL/DOI change breaks things

### ISSUE THREAD

**Issue by NicoRiedel** [smsaladi/jetfighter#8]
Biorxiv seems to have changed the structure of their URLs/DOIs by adding a date in the middle, e.g. 
https://www.biorxiv.org/content/10.1101/2019.12.17.879650v1.full.pdf
https://doi.org/10.1101/2019.12.17.879650 

This at least causes a problem in the SQL database where the ID field is to small now. I will check if there are more break points in the code.

**Comment by NicoRiedel** [comment]
I identified the following two lines (both related to the iiif server) where the new URL breaks things:

iiif-biorxiv/app.py: 
    paper_id = paper_id.split('.', 1)[0] -> splits now on the dots in the date

iiif-biorxiv/delegates.rb:
    fileid, sep, ext = fileid.partition(".") -> also splits the ID on the wrong place

I managed to get a quick fix by removing the whole line in the app.py file (was not sure why it was needed) and by changing fileid.partition(".") ->  fileid.partition(".pdf") (which is not optimal as it leaves an additional .full after the ID in the pdf filename)

So I think these are the relevant lines for now. Just need a better fix for this.

**Comment by smsaladi** [comment]
Thanks Nico. Might also help with displaying previews for barzooka -- fixed in https://github.com/smsaladi/iiif-biorxiv/commit/6ca22111e671b215b915dc4d8e988f35826276d5

and submoduled updated: https://github.com/smsaladi/jetfighter/commit/ca47740bce8e9173163b45802471a819fc149361
